### ISSUE TITLE
Ultrasonic Sensor Interfacing

### ISSUE THREAD

**Issue by mikeshams** [lokeshchinthakuntla/Project#3]
Parth - 1) What issues did you face when interfacing the ultrasonic sensor? 2) How did you resolve them? 3) Why did you switch from MCU EXPRESSOO to MBED? 4) Complete your code and demonstrate it as my request

**Comment by parthpatel10** [comment]
1) while interfacing ultrasonic sensor i used LCD display to display the distance sense by sensor. At first i tried with I2C protocol for display but didn't get anything on display. on further research i found another reference for LCD interfacing with LPC1768 using PWM output pins and after testing with that i got output as expected.  
2) we switch to MBED online compiler from MCUxpresso because we can take use of import program as well as libraries directly from the online catalogue from published program along with we can access it from anywhere and don/t need to switch between windows and Linux OS. Also MBED online compiler gives us directly .bin executable file that we just need to put in USB drive to check performance.
3) 
![WhatsApp Image 2020-11-08 at 11 33 33 PM](https://user-images.githubusercontent.com/54857091/98501328-d309de00-221c-11eb-9ea0-2be50915b2d8.jpeg)
