### ISSUE TITLE
LCD Interfacing

### ISSUE THREAD

**Issue by mikeshams** [lokeshchinthakuntla/Project#4]
Kunjalben - What issues did you face when interfacing the LCD to the MCU? 2) How did you resolve them?

**Comment by kunjalpatel2894** [comment]
[Fast and Effective Embedded Systems Design, Second Edition_ Applying the ARM mbed ( PDFDrive ).pdf](https://github.com/lokeshchinthakuntla/Project/files/5538491/Fast.and.Effective.Embedded.Systems.Design.Second.Edition_.Applying.the.ARM.mbed.PDFDrive.pdf)
First of all, we have used I2C protocol to interface LCD with LPC 1768, but we didn't get desired output. The code was working properly but there were no any data on the display, So we changed the communication protocol to PWM output. Trying with code and hardware implementation on PWM pins, we got the output on the screen.

**Comment by kunjalpatel2894** [comment]
One more issue was, in LCD when the obstacle was in the range of 2- 30cm, the output on the LCD was like Garbage level percentage" in the 2nd row and in the 1st row, there was a name of our project "Smart Bin" which was fixed for all the conditions. But while testing we got unexpected output when we moved our obstacle beyond 30cm. There was no any data in the 2nd row. This issue is resolved by setting the requirements like, when the obstacle is in the range of 2-30cm,  the display data is like, "Smart Bin"  in the 1st row and "Garbage percentage  "in the 2nd row. When obstacle is beyond 30cm, the 1st row is same "Smart Bin" and the 2nd row on the LCD display is "No data". So by setting this two different configuration , we got the appropriate output.

**Comment by kunjalpatel2894** [comment]
In LPC 1768, for PWM output we had very limited references of hardware implementation and especially for coding part. As PWM  works as Single edge PWM and double edged PWM, it was hard for us to figuring out which one is used. We found one reference where it showed all the necessary commands and explanation of PWM output and we decided to go with Single edge PWM and after implementation it worked well in our project.
