### ISSUE TITLE
Interfacing to the cloud

### ISSUE THREAD

**Issue by mikeshams** [lokeshchinthakuntla/Project#7]
Lokesh - Your Group and Group 6 used ESP 8266 to connect the project to the ThinghSpeak. They had to use Arduino IDE but you did not. Why? Answer this question in details.

**Comment by lokeshchinthakuntla** [comment]
1. interface ESP8266 to ARM the same way you would interface with any other MCU; by UART. You can send AT commands to the ESP8266 from the ARM controller via this method. And, it helps that the ARM (at least the LPC2148) is 3.3v logic level, so no level shifting required whatsoever. Of course, remember that you can instead program the inbuilt microcontroller (which is quite fast at 80Mhz; much, much faster than an Arduino) using the Arduino IDE or Micropython, NodeMcu firmware, or LUA Scripting. Of course, the Arduino method is the easiest. But if you have to interface it with an ARM microcontroller, send AT commands to the ESP8266 from your ARM controller to do everything from connecting to Wi-Fi and making HTTP requests.
Reference: https://www.quora.com/How-do-I-interface-ESP8266-to-ARM

1.Send AT commands from LPC2148 to ESP8266 to configure ESP8266 in AP mode
2.Connect the laptop or computer Wi-Fi with the ESP8266 Access point
3.Create an HTML webpage on PC with Access point IP address of the ESP8266 webserver
4.Create a program for LPC2148 to control the LED according to the value received from ESP8266

Setting up ESP8266 Circuit Board

ESP8266 requires a constant supply of 3.3V and it is not breadboarded friendly. So in our previous tutorial on ESP8266, we made a circuit board for ESP8266 with a 3.3V Voltage regulator, a RESET push-button, and a jumper setup for switching modes (AT command or flash mode). It can also be set up on a breadboard.
In order to interface ESP8266 with LPC2148, we must establish a UART serial communication between these two devices to send AT commands from LPC2148 to ESP8266 to configure the ESP8266 Wi-Fi module. To know more about ESP8266 AT commands follow the link.
So in order to use UART communication in LPC2148, we need to initialize the UART port in LPC2148. LPC2148 has two inbuilt UART ports (UART0 and UART1).
Reference: https://circuitdigest.com/microcontroller-projects/iot-based-ARM7-LPC2148-webserver-to-control-an-led#:~:text=Connect%20the%20laptop%20or%20computer,the%20value%20received%20from%20ESP8266

### **Using the ESP8266 to add Wi-Fi to the mbed LPC1768**
If you have the small ESP8266 module (and not the Huzzah or another module with the alternative Node MCU firmware), here are several basic WiFi demos to try on the LPC1768 mbed platform based on earlier examples from Paul Staron for a different mbed and different ESP8266 firmware. A terminal application program should be running at 115200 baud attached to your mbed's USB com port (the mbed com number varies). It will display the mbed WiFi commands and status messages sent out via mbed's USB virtual com port by the example programs. Teraterm sometimes gets in a mode where it displays bad characters at very high baud rates like 115200. RealTerm seems to be a more reliable option for these demos.

The first program will allow you to check if your setup is working and that you get a valid IP address from a WiFi router. After downloading the code to your compiler window, there is a line with your individual WiFi setup's "SSID" and "password" field that you will need to find and change, then recompile and download. This change is needed to connect to your WiFi and get an IP address. In this code, the SSID and password data is found in "main.cpp". Once you set it, the chip remembers it. Some WiFi security settings may require the MAC address of the device and this information is also displayed. So you need to run this first program first and get it working with a valid IP address for your ESP8266 before trying the second example. It displays status messages that will help, if there are problems with your initial Wi Fi setup.

Reference: https://os.mbed.com/users/4180_1/notebook/using-the-esp8266-with-the-mbed-lpc1768/
