### ISSUE TITLE
PCB Design

### ISSUE THREAD

**Issue by mikeshams** [lokeshchinthakuntla/Project#8]
Kunjalben - 1) what issues did you face when PCB Design? 2) what is the difference between a zero PCB and a finished PCB?

**Comment by kunjalpatel2894** [comment]
First of all, The schematic of our project was ready so we can directly convert the schematic into PCB, but few of the components did not have footprints. In order to design a PCB, it is necessary to have footprints of all the components. For that, I started PCB design from the scratch. I searched for the all components and their footprints and connected all the components in the PCB editor. The process was quite lengthy but I successfully created my PCB design.

**Comment by kunjalpatel2894** [comment]
While connecting the paths in the PCB editor, some of the paths were over-lapping each other. In order to make successful PCB design, it is required to figure out this issue. In EasyEDA, there is an option of Auto route. So Once I clicked on that, some connections created in the bottom layer which was a solution of our problem. So the connections were divided into top and bottom layer.

**Comment by kunjalpatel2894** [comment]
In EAsyEDA, there is a tool called DRC(Design Rule Check) , after completion of PCB design, the DRC is used to check the errors in the design. When I checked my Design, there was an error called "The clearance between two objects is less than the Design rule checking clearance". The error was caused because the trace started diagonally instead to starting straight to the left at that particular point. So to solve this issue, i readjusted the track and i kept distance between two tracks which has less clearance and the issue was solved.

**Comment by kunjalpatel2894** [comment]
The difference between Zero PCB and finished PCB
1) Zero PCB is mostly used in DIY products which has only holes for placing components and coppers in the board to do manual soldering for creating the circuit traces while the finished PCB comes in single layer, double layer, multilayer board. There have circuit layer, drill layer, solder mask layer, outline layer and so on on the board. 
2) Zero PCB has square and rectangle shape while finished PCB have many different surface treatment.
3) Zero PCB is mainly used by hobbyists and used for small projects and the finished PCB is for industrial use for complex projects. Finished PCB used everywhere and can be found inside any gadget…
4) Finished PCB are more costly than zero PCB  but are very easy to build while Zero PCB requires too much labor but are too cheap
